name:                dotfiles
version:             1.2.1
github:              "kaizhang91/dotfiles"
license:             BSD3
author:              "Kai Zhang"
maintainer:          "kaizhang91@foxmail.com"
copyright:           "Kai Zhang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/kaizhang91/dotfiles#readme>

dependencies:
- base >= 4.7 && < 5
- system-filepath >= 0.4
- optparse-applicative >= 0.14
- shelly >= 1.7
- text >= 1.2

library:
  source-dirs: src

executables:
  dotfiles:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dotfiles

tests:
  dotfiles-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dotfiles
