session_name: editor

windows:
  - window_name: main
    focus: true
    shell_command_before:
      - cd ~/projects
    panes:
      - focus: true
  - window_name: cmd
    shell_command_before:
      - cd ~/projects
    panes:
      - focus: false
