root:
  askformore: false
  autoclip: true
  autoimport: true
  autosync: true
  cliptimeout: 45
  editrecipients: false
  nocolor: false
  noconfirm: false
  nopager: false
  path: gpgcli-gitcli-fs+file:///home/kai/share/password-store
  safecontent: false
  usesymbols: false
  notifications: true
mounts: {}
version: 1.6.11-git+HEAD
