# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd beep extendedglob nomatch notify
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/kai/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

###############
# My
###############
# antigen-hs
source ~/.zsh/antigen-hs/init.zsh

# Environment Variables
export GOPATH=$HOME/apps
export PATH=$HOME/.local/bin:$GOPATH/bin:$PATH
export EDITOR=vim
export LANG=en_US.UTF-8
export LC_CTYPE=zh_CN.UTF-8     # 中文处理
export LC_COLLATE=zh_CN.UTF-8   # 中文排序
export TZ=Asia/Shanghai
export XDG_CONFIG_HOME=$HOME/.config
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'

# Prompt
local PR_USER PR_PROMPT PR_HOST

if [[ $UID -ne 0 ]]; then  # Normal user
    PR_USER='%F{green}%n%f'
    PR_PROMPT='%f➤%f'
else
    PR_USER='%F{red}%n%f'
    PR_PROMPT='%F{red}➤%f'
fi

if [[ -n "$SSH_CLIENT" || -n "$SSH2_CLIENT" ]]; then
    PR_HOST='%F{red}%M%f'  # SSH
else
    PR_HOST='%F{green}%M%f'  # No SSH
fi

local return_code="%(?..%F{red}%? ↵%f)"
local user_host="${PR_USER}%F{cyan}@${PR_HOST}"
local current_dir="%B%F{blue}%~%f%b"
PROMPT='╭─${user_host} ${current_dir} $(git_super_status)
╰─$PR_PROMPT '
RPROMPT='${return_code}'

# Alias
alias ls='ls --color'
alias tmux='tmux -2'
